version: '3.4'

services:
  webui:
    image: octavianmitu/cleanarhitecture
    build:
      context: .
    environment:
      - "UseInMemoryDatabase=${UseInMemoryDatabase}"
      - "${DB_CONNECTION_STIRNG}"
      - "IdentityServer__Key__Type=${IdentityServer_Key_Type}"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=${DB_PASSWORD:-Your_password123}"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "SpaBaseUrl=http://clientapp:4200"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOMR}/.aspnet/https:/https/:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure

  clientapp:
    image: octavianmitu/cleanarhitecture-frontend
    build:
      context: src/WebUI/ClientApp
    depends_on:
      - webui
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=${DB_PASSWORD:-Your_password123}"
      - "ACCEPT_EULA=${DB_ACCEPT_EULA:-Y}"
    ports:
      - "1433:1433"